apiVersion: v1
kind: Namespace
metadata:
  name: hornchat
---
apiVersion: v1
kind: Secret
metadata:
  namespace: hornchat
  name: hornchat
type: Opaque
data:
  OPENAI_API_KEY: <base64 encoded key>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hornchat
  name: hornchat
  labels:
    app: hornchat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hornchat
  template:
    metadata:
      labels:
        app: hornchat
    spec:
      containers:
        - name: hornchat
          image: <docker user>/hornchat:latest
          resources: {}
          ports:
            - containerPort: 3000
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: hornchat
                  key: OPENAI_API_KEY
---
kind: Service
apiVersion: v1
metadata:
  namespace: hornchat
  name: hornchat
  labels:
    app: hornchat
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: hornchat
  type: ClusterIP
